baseurl = "https://www.milanwiedemann.com/"
languageCode = "en-us"
title = "Milan Wiedemann"
theme = "hugo-ivy"
googleAnalytics = "UA-113145816-1"
disqusShortname = "milanwiedemann"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
enableEmoji = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

[[menu.main]]
    name = "Presentations"
    url = "/presentations/"
    weight = 3
    
[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 4
    
[[menu.main]]
    name = "Videos"
    url = "/media/"
    weight = 5
 
#[[menu.main]]
#    name = "Blog"
#    url = "/blog/"
#    weight = 5    
    
[[menu.main]]
    name = "CV"
    url = "/cv/cv-milanwiedemann.pdf"
    weight = 7
    
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 8

[params]
    description = "Experimental Psychology, Open Science, R"
    footer = "&copy; [Milan Wiedemann](/) 2019 | [Twitter](https://twitter.com/milanwiedemann) | [Google Scholar](https://scholar.google.co.uk/citations?user=MlR2ow4AAAAJ&hl=en) | [GitHub](https://github.com/milanwiedemann) | [OSF](https://osf.io/dycce) | [RG](https://www.researchgate.net/profile/Milan_Wiedemann)"
    
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
  