baseurl = "http://milanwiedemann.netlify.com/"
languageCode = "en-us"
title = "Milan"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = "milanwiedemann"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About me"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
[[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 4
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
#[[menu.main]]
#    name = "Subscribe"
#    url = "/index.xml"


    
[params]
    description = "Psychological Therapy, Open Science, Reproducibility, R"
    footer = "&copy; [Milan Wiedemann](/) 2018 | [Twitter](https://twitter.com/milanwiedemann) | [Google Scholar](https://scholar.google.co.uk/citations?user=MlR2ow4AAAAJ&hl=en) | [Github](https://github.com/milanwiedemann)"
    
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
  